pipeline {
    agent any
    tools {
        python 'Python 3'
    }
    environment {
        VENV = 'venv'
    }
    stages {
        stage('Clone repo') {
            steps {
                git credentialsId: 'github-credentials-id', url: 'https://github.com/ismailouzy/alx-backend-python.git'
                sh 'git branch'
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv $VENV'
                sh './$VENV/bin/pip3 install --upgrade pip'
                sh './$VENV/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh './$VENV/bin/pytest messaging_app/tests/ --junitxml=report.xml'
                junit 'report.xml'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t yourdockerhub/messaging_app messaging_app/'
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    sh 'docker push yourdockerhub/messaging_app'
                }
            }
        }
    }
}

